
version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - '${POSTGRES_HOST_PORT}:5432'
    volumes:
        - ./data:/var/lib/postgresql/data